#! /bin/sh
# https://github.com/NicolasCARPi/.dotfiles

bspc config border_width        1
bspc config window_gap         20

bspc config split_ratio         0.42
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

# hover with mouse get focus
bspc config focus_follows_pointer true

bspc config focused_border_color white
bspc config normal_border_color #2a2a2b
bspc config focused_locked_border_color red

if [ $(hostname) == 'kwala' ]; then
    bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8
    bspc monitor HDMI-1 -d 9
else
    bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9
fi

# filezilla always on 4
bspc rule -a Filezilla desktop=^4 follow=on

export PATH=~/.bin:$PATH
panel &
